### ISSUE TITLE
FMS Apache hostname/port can be different from FMS API

### ISSUE THREAD

**Issue by jbochi** [globocom/hlsclient#7]

**Comment by igorsobreira** [comment]
I'll implement the configuration file using YAML instead of ini files. Here is how the configuration could look like:

``` yaml
hlsclient:
  - destination: /tmp/hls

discover:
  backend: discover.discover_fms
  servers:
    - apache: http://fmsserver.mycompany.com:8134
      fms_admin:
        host: http://fmsserver.mycompany.com:1111
        user: fms
        password: secret
    - apache: http://fmsserver.mycompany.com:8134
      fms_admin:
        host: http://fmsserver.mycompany.com:1111
        user: fms
        password: secret
```
